### PR TITLE
make compatible with windows systems

### PR DESCRIPTION
**Pull request by webbertakken**
This will add a package that will simply add NODE_ENV.cmd as per https://stackoverflow.com/a/40967643/3593896.

It will add compatibility with Windows systems.

### CODE REVIEW

**Comment by sbussard** [comment]
I don't have windows to test this out on, but have you checked out this project?
https://github.com/kentcdodds/cross-env

**Comment by webbertakken** [comment]
I have. It is also one of the answers on the SO-question that i referenced above. I simply picked the one with the most votes. Either will work.

**Comment by sbussard** [comment]
My concern about using `win-node-env` is that it hasn't been updated for two years and it doesn't have a very high score on npms.io (40), whereas `cross-env` was updated two months ago and has a score of 87. That's usually the process I use to determine which libraries to use. I suppose that would be a good piece for a contributions doc. What do you think?

https://npms.io/search?q=win-node-env
https://npms.io/search?q=cross-env

**Comment by webbertakken** [comment]
I hadn't thought of that. I only had a look at the code, which is very manageable as it is only a few lines of code and therefore very light weight.

Would you like me to update the PR to work with cross-env instead?

**Comment by sbussard** [comment]
Yes please

**Comment by sbussard** [comment]
🎉🎉Thank you!! 🎉🎉

**Comment by sbussard** [comment]
closes issue #14

**Pull request merged**
